# Generated by Django 3.0.6 on 2020-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200525_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='min_text',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
