# Generated by Django 3.0.6 on 2020-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200525_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='min_text',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
    ]
